// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svxchtuecxqqsrdebvkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2eGNodHVlY3hxcXNyZGVidmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNDM1MjQsImV4cCI6MjA1MTYxOTUyNH0.ZkDZNDAseZGuplxIQkj0bIs8kTb_wP8kZcqJqebPnyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);